export type Animal = {
    idAnimal: number;
    uuid: string | null;
    idRefugio: number;
    idEspacio: number;
    espacioNombre: string | null;
    idEstado: number;
    estadoNombre: string | null;
    nombre: string | null;
    especie: string;
    raza: string | null;
    sexo: string | null;
    edadEstimada: number | null;
    peso: number | null;
    procedencia: string;
    rasgosFisicos: string;
    estadoInicial: string;
    fechaIngreso: string;
    activo: boolean;
    disponibleAdopcion: boolean;
    enCuarentena: boolean;
    esterilizado: boolean;
    deletedAt: string | null;
};